### ISSUE TITLE
Research and detail capabilities of static apiml for HA

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#478]
Can we:
Use http for a static apiml registration, instead of https?
Have multiple redundant servers (hot standby high availability) with static registration?
If we can have multiple, what do apiml queries return when we query statically registered 

If we can do all of this, then we may not need to make zss a dynamic eureka client.

**Comment by NakulManchanda** [comment]
Use http for a static apiml registration, instead of https?
- answer is yes, i tried this and so service do not have to https to start with
- api gateway layer can serve http as https

- we can try registering zss statically with apiml 

**http**
```
#
services:
    - serviceId: sample-node-api-http
      title: Sample Node API
      description: Example Node.js Application
      catalogUiTileId: sample-node-api
      instanceBaseUrls:
        - http://tvt5003.svl.ibm.com:18000/
      homePageRelativeUrl:  # Home page is at the same URL
      routedServices:
        - gatewayUrl: api/v1  # [api/ui/ws]/v{majorVersion}
          serviceRelativeUrl:
      apiInfo:
        - apiId: com.ibm.sample-node-api
          gatewayUrl: api/v1
          version: 0.0.1

catalogUiTiles:
    sample-node-api:
      title: Sample-Node-Api
      description: Example Node.js Application
```

**https**
```
#
services:
    - serviceId: sample-node-api-https
      title: Sample Node API 2
      description: Example Node.js Application
      catalogUiTileId: sample-node-api-2
      instanceBaseUrls:
        - https://tvt5003.svl.ibm.com:18001/
      homePageRelativeUrl:  # Home page is at the same URL
      routedServices:
        - gatewayUrl: api/v1  # [api/ui/ws]/v{majorVersion}
          serviceRelativeUrl:
      apiInfo:
        - apiId: com.ibm.sample-node-api-2
          gatewayUrl: api/v1
          version: 0.0.1

catalogUiTiles:
    sample-node-api-2:
      title: Sample-Node-Api-2
      description: Example Node.js Application
NAKUL:/u/nakul/zowe/extenders/sample-node-api
```
