### ISSUE TITLE
Determine merge logic rules for ha-instance

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#783]
How do you handle situations as complex as multi-lpar, multi-sysplex?

**Comment by 1000TurquoisePogs** [comment]
Merging works for non-ha stuff simply, it seems to be a case of traversal into a tree where objects attributes are overridden.
In a list of config files such as config=file(/a/b/c),file(/d/e/f), consider this:

/a/b/c:

```
components:
  app-server:
    logLevels:
    abc: 1
    def: 2
```
/d/e/f:

```
components:
  gateway:
    port: 111111
```

The end result should look like:

```
components:
  app-server:
    logLevels:
      abc: 1
      def: 2
  gateway:
    port: 111111
```


Consider this second case, in which we have a default file (default.yaml) and a file that overrides it (custom.yaml)

custom.yaml:

```
app-server:
  logLevels:
    abc: 1
    def: 2
```

default.yaml:

```
app-server:
  logLevels:
    def: 3
    zzz: 5
```

The result is:

```
app-server:
  logLevels:
    abc: 1
    def: 2
    zzz: 5
```
