### ISSUE TITLE
Help needed: use own certificates held in RACF keystore

### ISSUE THREAD

**Issue by lv198** [zowe/zlux#954]
Hello,

I have trouble getting Zowe V2.5 to work with our own certificates generated by our own CA. We are not using any certificate configuration provided by Zowe, because we have our own processes for that purpose.

What's working: I can access Zowe Desktop via Browser (and our valid certificate) and I can log on. So it seems that it can read the correct certificate from the keystore.
What's not working: everything else. For example, I get these messages every 10 seconds:
```
error initing session: 17                                                     
failed to obtain JWK, status = 9                                              
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 10 seconds
```
But I also can not use any app on the desktop (for example, opening JES Explorer results in a useless logon-screen).

This is my current certificate configuration in zowe.yaml (a bit anonymised):
```
certificate:                                         
  keystore:                                          
    alias: ZOWE_SERVER                               
    password: password                               
    file: safkeyring://ZWESVUSR/Keyring          
    type: JCERACFKS                                  
  truststore:                                        
    type: JCERACFKS                                  
    file: safkeyring://ZWESVUSR/Keyring          
    password: password                               
  pem:                                               
    key:                                             
    certificate:                                     
    certificateAuthorities:                          
      - safkeyring://ZWESVUSR/Keyring&OUR ROOT CA
      - safkeyring://ZWESVUSR/Keyring&OUR SSL CA 
verifyCertificates: DISABLED  
```
